#!/usr/bin/env python2

# Copyright (c) 2014 ARRIS Enterprises, Inc. All rights reserved.
#
# This program is confidential and proprietary to ARRIS Enterprises, Inc.
# (ARRIS), and may not be copied, reproduced, modified, disclosed to others,
# published or used, in whole or in part, without the express prior written
# permission of ARRIS.

import os
import re
import sys


class ExpansionError(Exception):
    pass


def expand_in_dir(path):
    macros = {
        'EXPORT': '__attribute__ ((visibility("default")))',
        'LOCAL': '__attribute__ ((visibility("hidden")))',
        'EXPORT_BEGIN': '#pragma GCC visibility push(default)',
        'EXPORT_END': '#pragma GCC visibility pop',
        'LOCAL_BEGIN': '#pragma GCC visibility push(hidden)',
        'LOCAL_END': '#pragma GCC visibility pop'
    }

    for dirpath, dirs, files in os.walk(path):
        for name in files:
            if name.endswith('.h'):
                expand(macros, os.path.join(dirpath, name))


def expand(macros, h_file):
    tmp_file = h_file + '.tmp'
    with open(tmp_file, 'w') as fout:
        with open(h_file, 'r') as fin:
            for line in fin:
                if not line.lstrip().startswith('#'):
                    for macro, expansion in macros.iteritems():
                        line = re.sub(r'\b' + macro + r'\b', expansion, line)
                fout.write(line)
    os.rename(tmp_file, h_file)


def main():
    data_dir = sys.argv[1]

    if not os.path.exists(data_dir):
        raise ExpansionError('Path does not exist: ' + data_dir)

    expand_in_dir(data_dir)


main()
