// Copyright (c) YEAR ARRIS Enterprises, Inc. All rights reserved.
//
// This program is confidential and proprietary to ARRIS Enterprises, Inc.
// (ARRIS), and may not be copied, reproduced, modified, disclosed to others,
// published or used, in whole or in part, without the express prior written
// permission of ARRIS.
//
// This file was generated by createmock from ITest.h.
//
// DO NOT EDIT, CHANGES WILL BE LOST!

#include "TMockTest.h"

Kvast::Fening::TNaggyMockApelsin::TNaggyMockApelsinObserver::TNaggyMockApelsinObserver()
  : EnableDestructorMocking(false)
{
  // Intentionally empty
}

Kvast::Fening::TNaggyMockApelsin::TNaggyMockApelsinObserver::~TNaggyMockApelsinObserver() throw (TCitrus)
{
  if (EnableDestructorMocking) {
    // Only call Die() when wanted. This reduces log spam.
    Die();
  }
}

Kvast::Fening::TNaggyMockApelsin::TNaggyMockApelsin()
  : EnableDestructorMocking(false)
{
  // Intentionally empty
}

Kvast::Fening::TNaggyMockApelsin::~TNaggyMockApelsin() throw()
{
  if (EnableDestructorMocking) {
    // Only call Die() when wanted. This reduces log spam.
    Die();
  }
}

Kvast::Fening::TNaggyMockBanan::TNaggyMockBanan()
  : EnableDestructorMocking(false)
{
  // Intentionally empty
}

Kvast::Fening::TNaggyMockBanan::~TNaggyMockBanan()
{
  if (EnableDestructorMocking) {
    // Only call Die() when wanted. This reduces log spam.
    Die();
  }
}
